### ISSUE TITLE
revert-buffer corrupts visibility

### ISSUE THREAD

**Issue by tarsius** [tj64/outshine#21]
The use of `revert-buffer` corrupts the visibility of sections. Ideally the same sections would be expanded/collapsed as before the revert, but I can live without that. However after a revert even some top-level sections disappear. I have to collapse and then expand everything just to get all the top-level section **headings** back.

**Comment by alphapapa** [comment]
> I am pretty sure this is not outshine specific. Do you have a link to that conversation? Maybe it contains some hints on how this could be done (not that I intend to tackle this any time soon).

I guess you're right, as I've run into the same issue myself in `helm-navi`.  I don't know how to persist the buffer visibility, even across `show-all`.  But I'm pretty sure that I have noticed the buffer visibility being preserved in some other modes or situations, so maybe there is a way...

**Comment by tarsius** [comment]
> so maybe there is a way...

Yes, but I fear that involves caching the visibility before the revert, reverting, and then restoring as much state as possible.

Anyway, I don't use `outshine` anymore and this isn't the official repository anymore, so I am closing this. I actually plan to work on this eventually, but if I do, then I will teach `outline.el` to do it.
