### ISSUE TITLE
Erratic behavior

### ISSUE THREAD

**Issue by tmalsburg** [tj64/outshine#37]
Outshine sounds extremely useful but unfortunately I can't get it to work.  Following the documentation, I configured outshine as following (installed from MELPA using the current development version of Emacs from git):

```
(require 'outshine)
(add-hook 'outline-minor-mode-hook 'outshine-hook-function)
(add-hook 'emacs-lisp-mode-hook 'outline-minor-mode)
(add-hook 'LaTeX-mode-hook 'outline-minor-mode)
```

The I tested with the following file (test.el):

```
;; * test 1
(message "This is test 1.")
;; * test 2
(message "This is test 2.")
```
- When I place the cursor on "test 1" and execute `M-x outline-cycle`, I get a message "before first heading" and nothing else happens.
- When I place the cursor at the beginning of line 1 and execute `M-x outline-cycle`, I get the following
  ;; \* test 1
  ...
  
  But I can't make the material hidden behind ... reappear by repeatedly executing `outline-cycle`.
- When I place the cursor on "test 2" and `M-x outline-cycle`, the cursor jumps to the beginning of line 2.  Nothing else happens.
- When I place the cursor on line two (on "message") and `M-x outline-cycle`, I get the following:
  
  ;; \* test 1
  (message "This is test 1.")...
  (message "This is test 2.")
- When I place the cursor on line four (on "message") and `M-x outline-cycle`, I get a message "CHILDREN" and nothing else happens.

**Comment by naupaka** [comment]
For those looking for the answer to this - I found I had to have two `##` in order for headers to be picked up properly in ESS mode (R files). One `#` gave the same errors as above.

```
outline-regexp is a variable defined in ‘outline.el’.
Its value is "## [*]\\{1,8\\} "
Local in buffer temp.R; global value is "[*\f]+"
```
