### ISSUE TITLE
Don't mess with imenu-generic-expression

### ISSUE THREAD

**Issue by tarsius** [tj64/outshine#41]
Outshine replaces the default value of `imenu-generic-expression` instead of modifying it. I assume you do that because if "new-style" headers are used, then the entry which works with "old-school" headers won't do. If that is so, you should determine that entry and replace it, and you would only have to do so if "new-style" headers are used. Currently outshine just discards the old value which is no good in modes, like `emacs-lisp-mode`, which come with nice values for that variable.

**Comment by tj64** [comment]
Hi, after quite a long absence form Emacs (Lisp) I don't even understand the problem anymore ;-)
So I just close the issue, I think your comments can serve as a reference for others interested in the topic. Thanks - and sorry for not really dealing with this!
