### ISSUE TITLE
(require 'outshine) breaks org-global-cycle

### ISSUE THREAD

**Issue by bradyt** [tj64/outshine#45]
If I start `emacs -q`, and do `package-initialize` and `(require 'outshine)`, then open an org buffer and do `org-global-cycle`, I get "Before first heading", regardless of where I am. 

My version is 20141221.1805, which appears to be current. 

I am on 8.3beta org-mode, but occurs in 8.2.10 also.

**Comment by kaushalmodi** [comment]
Pull request https://github.com/tj64/outshine/pull/46 fixes this.

**Comment by alphapapa** [comment]
@tj64 You can close this if you like.  :)
