### ISSUE TITLE
How to diable outshine for latex mode

### ISSUE THREAD

**Issue by QiangF** [tj64/outshine#47]
Hello everyone,

I am new to emacs, I am wondering if we can add extra headings to different mode and keep the default outline-minor-mode heading. These heading has the format like this
spaces+comment_character+ * heading_level_1
spaces+comment_character+ ** heading_level-2
...
the comment_character is the mode dependant, then we can add those to the outline extra for that mode. The benifit is: the heading can have indentation before it, so we can have different levels in a python function.  
From what I have read, it seems that we need to modify outline-regex for every mode affected, it will be wonderful if someone can find an easier way to add the extra level one heading to every mode.
Thank you for your help.

**Comment by tj64** [comment]
Not sure if I understand, but outshine calculates the heading from a major mode's comment syntax. If you want different headings, mybe clone the mode and change the comment-syntax?

Outshine is like Org. If you want a totally flexible file overview, you could use navi-mode, you can customize it for any mode as you like.
