### ISSUE TITLE
outshine-narrow-to-subtree works only if it is on the Heading

### ISSUE THREAD

**Issue by shankarpdy** [tj64/outshine#48]
To make it work anywhere, I added a function-here, but it is not generic

(defun outshine-find-narrow-to-subtree () ;;Added by Shankar
    (interactive)
    (beginning-of-line)
    (setq myStr (thing-at-point 'line))
    (message "The collected string is %s" myStr)
    (when (string-match "^// * " myStr)
      (outshine-narrow-to-subtree)
    )
    (when (not (string-match "^// * " myStr))
       (search-backward-regexp "^// *" nil t)
       (outshine-narrow-to-subtree)
    )
)

**Comment by tj64** [comment]
Ok, thanks, this can serve as reference for anybody who wants to use this function.
