### ISSUE TITLE
enabling outshine causes company-mode popups to not show

### ISSUE THREAD

**Issue by goldie103** [tj64/outshine#49]
Starting Emacs with this minimal init file and turning on `outline-minor-mode` causes [company-mode](https://github.com/company-mode/company-mode) completion popups to never show. Turning off `outline-minor-mode` or removing the hook to `outshine-hook-function` gets company popups working again.
```lisp
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
(package-initialize)

(require 'company)
(global-company-mode t)

(require 'outshine)
(add-hook 'outline-minor-mode-hook #'outshine-hook-function)
```
I don't know enough Elisp to know why this happens and I understand this isn't being maintained at the moment, but I thought this might be good to know for anyone else having this problem.

**Comment by goldie103** [comment]
Again, for anyone else having the problem, I've isolated it to `outshine-self-insert-command`. Commenting out the two lines mapping `self-insert-command` to `outshine-self-insert-command` fixes the problem (judging by the documentation of the function, this comes at the expense of tables no longer working).

**Comment by tj64** [comment]
Do you have the same problem in Org-mode? IIRC, this part of outshine is just a port of Org functionality.

**Comment by goldie103** [comment]
Nope; if I enable Org-mode and manually select a backend with `company-begin-backend`, then completion popups show as expected.

**Comment by csantosb** [comment]
Does #38 fixes the problem ? It does for me.

**Comment by goldie103** [comment]
Ah, it does. I could've sworn I'd done a search for anyone else having the problem but I must've missed that one. Thanks!
