### ISSUE TITLE
MELPA package broken

### ISSUE THREAD

**Issue by julienfantin** [tj64/outshine#55]
The new files are missing from the MELPA recipe.

**Comment by emacs18** [comment]
Currently the outshine package on melpa.org seems to have just one file in it,
i.e., outshine.el. The package does not include outshine-org-cmds.el file even
though it is required by outshine.el.

Hence the following change I think should be made to fix the recipe at
https://github.com/melpa/melpa

```
diff --git a/recipes/outshine b/recipes/outshine
index 0d88cc0..48f15c7 100644
--- a/recipes/outshine
+++ b/recipes/outshine
@@ -1 +1 @@
-(outshine :fetcher github :repo "tj64/outshine" :files ("outshine.el"))
+(outshine :fetcher github :repo "tj64/outshine" :files ("*.el"))
```

If you agree, then I can submit a pull request at
https://github.com/melpa/melpa

**Comment by tj64** [comment]
Yes please, go ahead, but outline-mode-easy-bindings.el is not needed actually, its already fully integrated into outshine.el and only there for historical reasons.
Sorry for breaking the package, please let me know about the state of things.

**Comment by tj64** [comment]
I made a pull request myself already ...

**Comment by julienfantin** [comment]
Thanks Thorsten, and glad you've resumed your work on outshine it's been extremely useful!

**Comment by tj64** [comment]
Thanks Julien,
at least I started to take care of outshine again ,.. and luckily  in one of the new issues, spacemacs was mentioned, a wonderful project, and currently I'm trying the transition from my home-brew config to spacemacs (and to vim bindings), I wouldn't have discovered it without maintaining outshine again ;-)

**Comment by emacs18** [comment]
If you are interested in spacemacs, then perhaps you can take over
writing of spacemacs layers for your packages.  I started writing
my own layer which is just a directory with config.el and packages.el
files.  For now config.el is empty, and packages.el has these lines
where the layer is named "my-navi" for my own use.  Perhaps you can take
this and write a proper layer and submit a pull request to spacemacs?

```
;;; packages.el --- packages needed by my-navi


(setq my-navi-packages '(outshine outorg navi-mode))

(defun my-navi/init-outshine ()
  (use-package outshine
    :defer t :init
    (progn
      (add-hook 'outline-minor-mode-hook 'outshine-hook-function)

      (add-hook 'emacs-lisp-mode-hook 'outline-minor-mode)
      (add-hook 'LaTeX-mode-hook 'outline-minor-mode)
      (add-hook 'message-mode-hook 'outline-minor-mode)
      )))

(defun my-navi/init-outorg ()
  (use-package outorg
    :defer t :init
    (progn
      )))

(defun my-navi/init-navi-mode ()
  (use-package navi-mode
    :defer t :init
    (progn
      )))
```

**Comment by tj64** [comment]
Yes, I thought about this already, but since I'm more a casual Emacs user at the moment I'm still struggling a bit with spacemacs. When I managed to port my config to spacemacs and got used to vim-style editing I will tackle this ...
