### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by TLINDEN** [tj64/outshine#59]
Hi,

maybe a silly question, but I don't really understand how to actually use outshine. It's loaded but not working as I expect it.

Actually I want to organize my .emacs file with it, I want to have several sections in it so that I can find them easier. But there's no mention anywhere how the headings have to look exactly, only that there have to be headings.

So far, I've got this:
```
;;; one
;;;; two
;;;;; three
```
I can point to 'one' and use TAB to expand/collapse them. But there's no special highlighting or anything, every heading has the comment face. Also it only works if I have an empty ;;; comment on top of the file, otherwise TAB doesn't work at all.

I also tried things like ```;; * heading``` to no avail.

And it only works this way in elisp files, it doesn't at all in python or c files (while loaded and active). For example if I execute 'outshine-insert-heading' it just inserts an empty line with point at char 0 in python, in elisp it just creates a new empty comment line.

I'm confused.

So, I'm asking you to put an example outlined file into the documentation so that people know where to start - or point to somewhere else where to look for this.

**Comment by tj64** [comment]
Hi, all 3 libraries from the outshine suite are themselves examples for stucturing an Elisp file the outshine way (with oldschool headers like the ones you used above).

Here I demonstrate outshine/navi-mode with my init.el in a youtube screencast:

     [navi-mode demonstration](https://www.youtube.com/watch?v=gzf2HeOZLw0)

that should give you a good idea.
And its actually rather easy - a programming mode file structured the outshine way looks exactly like an org-mode file, only with outcommented text/headlines. Therefore you can use outorg to switch between two views on the same file

- outshine view: text outcommented, code is default
- org-mode view: code wrapped in source-blocks, test is default

To make it work its important to follow the installation procedure described in the README of outshine and the other libs.

HTH

-

**Comment by TLINDEN** [comment]
Well,  using ```;; *``` doesn't work at all. ```;;;``` works but it doesn't apply different faces for different heading levels.

**Comment by tj64** [comment]
Did you actually read the README and follow the installation
instructions for outshine?
You describe the behaviour when outline-minor-mode is active without
outshine extensions.

You can only have one of the two headline styles in one buffer, don't
mix them. 

Did you set the outshine hooks in your .emacs?

What does C-h v outline-regexp say in an emacs-lisp buffer with outshine
headers (;; * )?

**Comment by TLINDEN** [comment]
You're right, I forgot:
```(add-hook 'outline-minor-mode-hook 'outshine-hook-function)```
Sorry :(

And thanks for the help!


Tom
