### ISSUE TITLE
FYI: helm-navi and helm-outshine

### ISSUE THREAD

**Issue by alphapapa** [tj64/outshine#64]
FYI, I thought you might be interested in this PR I just made: https://github.com/emacs-helm/helm/pull/1728  It presents outshine and navi headings and keywords in Helm, which makes it really fast to filter and jump to certain places when you don't need a persistent occur view.

Thanks a lot for your work on outshine/outorg/navi, they make navigating elisp files a pleasure.  :)

**Comment by tj64** [comment]
Hi, thank you. 
I'm afraid I'm a lousy maintainer for quite some time, since I only occasionally use Emacs now (not that I don't like it anymore, its just a lack of opportunity.
So when somebody reports a bug or a feature request, for me its like being called to work for free, in my freetime  - not very motivating. When I was still an eager daily emacs/org-mode/outshine user, I had a strong self interest in fixing bugs and adding features, but now?

I wish somebody would be willing to take over maintainership for these libraries. 
OTOH - when ever I try, they just work for me. This is not buggy abandon-ware, but still working software as far as I can tell ....
Cheers

**Comment by rgrinberg** [comment]
@tj64 First of all, thanks for maintaining this great package. outshine has been really useful to me. I understand that you no longer have time to maintain outshine. What about polling some of your contributors to see if they'd like to help maintain this great package?

Checking your list of contributors, I see some fine candidates: @tarsius @vapniks @ggreif @syohex

**Comment by alphapapa** [comment]
@tj64 Like @rgrinberg said, thank you for your outstanding work on this package.  I haven't contributed to Outshine before, so I'm probably not qualified to be the sole maintainer, but I would be glad to help maintain it.  I've been using it for a long time, and I think it will become more important to my workflow in Emacs now.

**Comment by tj64** [comment]
Hi alphapapa,
I would be glad if someone who is a daily user of outshine (i.e. outshine/outorg/navi), like I was before, of course with Elisp programming skills, would like to take over this suite of packages as a maintainer.

I have not given up hope that someday I can use wonderfull Emacs again as my principal software tool, but now I spend my days inside other tools and don't have the time and energy to do much with Emacs in my freetime.

Don't know how to achieve a change in maintainers though. Would you like to fork these 3 repos from me, and I put in the README that your repos are the official ones now?
And then we announce it in Org-mode and Emacs Help mailing lists?

I mean, I'm such a lousy maintainer right now, when these packages are really in use by some Emacs enthusiasts, they would deserve something better.

There is even some real hidden gem there, that would allow turning outshine into a true org-minor-mode: the outshine-use-outorg function.

I already used it for some Org-mode functionality, and prepared the path for making all of Org-mode's functionality available in Outshine (as long as it makes sense of course). Look into the sources, and you find a lot of well organized but still outcommented function skeletons, that only wait for being implemented. Several working examples show how it works.

Cheers

**Comment by rgrinberg** [comment]
>Don't know how to achieve a change in maintainers though. Would you like to
>fork these 3 repos from me, and I put in the README that your repos are the
>official ones now? And then we announce it in Org-mode and Emacs Help mailing
>lists?

IMO, it would make more sense if you simply gave push rights to a few people
you'd trust to do some maintenance work MELPA releases. E.g. like that list I
mentioned above.

I think this is a much more sustainable approach for 2 reasons:

* Users will usually only look at the main fork of the repo (yours) and only
report bugs there

* Similarly, contributors will usually make PR's against your fork and not be
aware of the development that's going on in other forks.

**Comment by tj64** [comment]
Yes you are right.
And maybe someday I come back as a user and can do more maintaince again too.

So I should contact some contributors, if they are willing to do some maintainance?
Would you two (alphapapa and you) like to have push rights?

**Comment by alphapapa** [comment]
@rgrinberg Has some good points, and I think team maintainership could be good.  However, the users he suggested have only made 2-3 commits each, and some very minor (and I think @tarsius and @syohex are busy enough already ;).

Transitioning maintainership to a new fork is actually not a big deal on GitHub.  I've done it before (although with a relatively obscure package compared to these).  If the original maintainer updates his fork's readme to point to the new repo (and be otherwise empty), then everyone who visits the original repo can't help but follow the link to the new fork.  Then, in the case of e.g. MELPA, we file a PR to update the recipe to point to the new fork, and the new maintainer updates the URLs in the new fork, etc.

Anyway, if @rgrinberg is interested in helping to maintain these packages, I'd be glad to join him in that, although since we don't know each other, I suppose we could have different preferences about coding style, future plans, etc.  :)  

I'd also be glad to assume maintainership of the packages myself.  No promises about polishing those hidden gems (I looked at them, and you're right, there's a lot of potential there!), but I think I have enough time to keep them running with Emacs, Org, etc, and do some enhancement now and then.  And since I'm using Outshine and Navi as part of my normal Emacs config, and now have published a Navi-related package, I think I'll be using them enough to notice problems.

**Comment by tarsius** [comment]
> and I think @tarsius [is] busy enough already

Yep. Also I don't currently use `outshine`. I might start using it again, but I am not interested in maintaining it.

**Comment by tj64** [comment]
A new main maintainer would be my perferred solution, and if you are willing to do that - perfectly.
Anyone interested (plus me) could the cooperate with you, but you take the final decisions etc.

**Comment by rgrinberg** [comment]
> Has some good points, and I think team maintainership could be good. However, the users he suggested have only made 2-3 commits each, and some very minor (and I think @tarsius and @syohex are busy enough already ;).

I'm only against having a fork rather than you assuming maintainership btw. If you're the only one willing to step up then I definitely think you should be the new maintainer.

But I'm curious do you prefer a fork over maintaining tj64's original repository? I've listed a couple of advantages of keeping the single main repository and I'd like to add that any maintainers will be relying on tj64's advice and answers. Seems like a fork is counter productive.

> Anyway, if @rgrinberg is interested in helping to maintain these packages, I'd be glad to join him in that, although since we don't know each other, I suppose we could have different preferences about coding style, future plans, etc. :)

I'm mostly interested in fixing up some bugs in outshine that bother me and perhaps adding a few features that I find missing. In short, just scratching my own issues. I definitely don't have the time for more participation than that.

**Comment by tj64** [comment]
If I would give alphapapa push rights to the 3 repos - would that be just as good as a de facto maintainer change?
@alphapapa : Or what would the new maintainer in Spe prefer? ;-)

**Comment by alphapapa** [comment]
> A new main maintainer would be my perferred solution, and if you are willing to do that - perfectly.
Anyone interested (plus me) could then cooperate with you, but you take the final decisions etc.

Ok, I'm willing to do that, and of course I would welcome any future contributions from you.  And who knows, if someday you wanted to resume maintainership, I'd be open to that as well.  :)

I'll go ahead and fork the packages and update the readmes to note the change, and when it looks good to you, you can update your readmes to point to the new forks.  Then I'll submit PRs to MELPA for the updated recipes, Cc'ing you on them.

> But I'm curious do you prefer a fork over maintaining tj64's original repository? I've listed a couple of advantages of keeping the single main repository and I'd like to add that any maintainers will be relying on tj64's advice and answers. Seems like a fork is counter productive.

Well, the way GitHub is set up, with each repo being under an individual account (unless an organization is setup), I think it makes for a cleaner transition to point to a new fork under another user account.  As long as the original repo makes it obvious where the new fork is, and that the old one exists as an archive and signpost, confusion shouldn't be an issue.  If the original maintainer is really intending to step away and not "own" the packages anymore, then I think it's better for them to be maintained under the new maintainer's account, that way they don't depend on the GitHub account of the former maintainer, and it lets him "bow out gracefully."  :)

**Comment by rgrinberg** [comment]
It's not really convincing to me. If the original maintainer's ownership of the github account, that's when you can always take the steps you've mentioned (you do have push rights). As for the rest, you're only arguing for mitigating the issues I've pointed out. But I think that avoiding them altogether is clearly best.

**Comment by alphapapa** [comment]
I really don't think there's any issue.  For example, I assumed maintainership of https://github.com/alphapapa/mpdsync, which was forked from https://github.com/nickpegg/mpdsync.  As you can see, the original repo only points to the new one, so no one will accidentally use the old one.

**Comment by tj64** [comment]
Ok alphapapa, you are the man, thanks for your engagement, and good luck as the new maintainer!
Lets do it the way you wrote, let me know when its my turn for some action.
So from now on you take the decisions about those packages, and I'm just an occasional user.

@rgrinberg 
there a valid arguments on both sides here, but I've seen packages swichting owner just the way alphapapa describes it, and if he is willing to take over ownership, it should go the way he perfers IMO.
And I too think its pretty common, since it reflects personnal engagement.

**Comment by alphapapa** [comment]
Ok Thorsten, thank you for your trust and for all your work on these packages up til now!  I'll do my best to take good care of them.  I'll post again here when I have updated my forks' readmes and such.

@rgrinberg I appreciate your interest in the packages, and I welcome any contributions from you in the future!  :)

**Comment by tj64** [comment]
Perfect!

**Comment by alphapapa** [comment]
I think that's everything.  Please check the diffs of the readmes/documentation if you like and make sure you're satisfied with where/how your name remains credited.  :)

**Comment by tj64** [comment]
Looks fine to me.
There was once a request from Stefan Monnier to add the Outshine packages to ELPA, but I did not quite want to. 
But I did start a contributor file, that listed all contributors with their contributions and their FSF Paperwork state, to keep this as an option for the future.
Just to let you know, I leave it to you how to deal with this.

I will adapt the README's now, and we are done, I would say.
Thanks a lot for your engagement!

**Comment by tj64** [comment]
Ok, done, my repos now point to yours.
Good luck!

**Comment by alphapapa** [comment]
Thanks, Thorsten.  :)

I will probably send in the FSF paperwork someday, as I was planning to try to contribute org-bookmark-heading to org-mode, and they seem receptive.

I feel like I would need to have a much deeper understanding of the package before I could offer it to ELPA as my own package, as that seems like a hefty responsibility.  But someday, perhaps.  And of course if Stefan wanted to take it as-is, as a kind of fork or snapshot, I'd be fine with that, although I doubt that's what they'd want.  So...someday...  :)

**Comment by tj64** [comment]
@alphapapa 
As much as I appreciate your engagement in taking over maintainership of these libraries, I find it a bit irritating that you put yourself as (first) AUTHOR in the README(s) of the forks, because thats obviously far from reality, and I think it's important to be fair here (I always tried to be fair in marking all contributions from others as such).

Main authors of these libraries are me and Carsten Dominik (in the sense that quite a lot of his outline-magic and org-mode coding made its way into the libraries, he never actively participated in the libraries developement). Then come other contributors who offered some functions and bug fixes.

Once you start fixing bugs and coding new functionality, you obviously become a contributor (and author) too. But putting yourself as author on top of the README gives a very misleading impression. There it should definitely say MAINTAINER, while in the MetaData you obviously should add yourself to the authors list once you did contribute to the coding (but again, not necessarily as the main author at the beginning of the list, if you just contributed a few lines of code or so).

Just try to be fair when it comes to give credits please.
Cheers 
Thorsten

**Comment by alphapapa** [comment]
Sorry for the misunderstanding here, I'm not trying to take credit away from you, I'm trying to avoid directing issues, bug reports, etc. toward you.  

I did a search/replace on those metadata blocks.  That's why I asked in the comment https://github.com/tj64/outshine/issues/64#issuecomment-291008360 to "make sure you're satisfied with where/how your name remains credited," and then you said that it looked fine to you.  I haven't changed any credits since then.  I also list you as the `original_author` in the CONTRIBUTORS files and list myself as only `principal_developer maintainer`.

If you are still dissatisfied with how you or others are credited, I will gladly change it.  Please note that I as I update the readmes and convert them to Org format, I am reorganizing them as well and don't have a dedicated "metadata" section.  I will be adding "Credits" sections to explain who has authored and contributed to the packages in the past.

Thanks.

**Comment by tj64** [comment]
Yes, I said it looks ok, but it seems I did not look well enough. By all common standards, the marked yellow parts in the following image are just completely misleading (are you the author of these libraries?):  

![image](https://cloud.githubusercontent.com/assets/434280/25052853/3b5df036-2154-11e7-94a2-616efd878ff4.png)

As I said: it's perfectly ok to put yourself as MAINTAINER in a prominent position of the README, and add yourself as author at the end of the list once you started contributing code to the libraries. You might even move step by step to front if the authors list if you contribute more and more and finally are the main author.

But keep things real please. Feel free to reorganize and do what you want (you are the maintainer!), but use common sense and standards in doing fair crediting. 
Thanks

**Comment by alphapapa** [comment]
I've changed "author" to "maintainer" wherever my name is mentioned.  Is this acceptable to you?  If not, let me know what changes you would like.

Again, in no way has it been my intention to take credit away from you or take credit for myself for work I haven't done.

**Comment by tj64** [comment]
Ok, this looks more realistic to me, thanks.
These are several thousands lines of code, it's kind of hard work to become the main (or one of the main) author(s) of this, so one should avoid misunderstandings with regards to credits.

Thanks again
Cheers Thorsten
