### ISSUE TITLE
Breaks org-store-log-note

### ISSUE THREAD

**Issue by alphapapa** [tj64/outshine#66]
Hi,

I upgraded Outshine today and now I get this error when I try to store a log note in Org mode (like in an agenda buffer):

```
outshine-mimic-org-log-note-marker: Symbol's function definition is void: org-log-beginning
```

It prevents me from storing or canceling the note.

I'm using Org 8.2.4, so maybe that's the problem, but I use a variety of Org-related packages, and I haven't had a problem like this before.  I've had to work around this for now by commenting out the `(defadvice org-store-log-note (around org-store-log-note-around activate) ...`.

Thanks for your work on Outshine!

**Comment by tj64** [comment]
Hi, 
look at this thread:

https://lists.gnu.org/archive/html/emacs-orgmode/2016-02/msg00123.html

I had to change outshine here, because org-mode changed.
Guess you should update Org, to make the problem go away.
Cheers 
Thorsten

**Comment by alphapapa** [comment]
Thanks, I will look into it.  I see that you asked at the time which Org version the change occurred in, so you could add a version check, but you didn't get an answer.  I will see if I can find out and send a PR with a version check.  :)

**Comment by alphapapa** [comment]
I checked the Org repo, and it looks like Org 8.3 is the first tagged version that has `org-log-beginning`: http://orgmode.org/w/?p=org-mode.git;a=commit;h=74e35a9154233676c8355068bea32d43490ce077
